### ISSUE TITLE
Can not run server image

### ISSUE THREAD

**Issue by FANGOD** [JacobLinCool/playwright-docker#7]
docker run --rm -p 53333:53333 jacoblincool/playwright:chromium-light-server-1.48.1
```Unable to find image 'jacoblincool/playwright:chromium-light-server-1.48.1' locally

chromium-light-server-1.48.1: Pulling from jacoblincool/playwright
Digest: sha256:20dbfe519ed12531c9bc3e829a0155189205932c85de4110247425f8a1460b96
Status: Downloaded newer image for jacoblincool/playwright:chromium-light-server-1.48.1
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

ProtocolError: Protocol error (Browser.getVersion): Internal server error, session closed. Failed to launch browser.
<launching> /usr/bin/chromium --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding,ThirdPartyStoragePartitioning,LensOverlay,PlzDedicatedWorker --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --headless=old --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-gBHnPg --remote-debugging-pipe --no-startup-window
<launched> pid=18
[pid=18][err] Error relocating /usr/lib/libgio-2.0.so.0: statx: symbol not found
[pid=18][err] Error relocating /usr/lib/libmount.so.1: statx: symbol not found
[pid=18] <process did exit: exitCode=127, signal=null>
[pid=18] starting temporary directories cleanup
    at /server/node_modules/playwright-core/lib/server/chromium/crConnection.js:135:16
    at new Promise (<anonymous>)
    at CRSession.send (/server/node_modules/playwright-core/lib/server/chromium/crConnection.js:131:12)
    at CRBrowser.connect (/server/node_modules/playwright-core/lib/server/chromium/crBrowser.js:51:35)
    at Chromium.connectToTransport (/server/node_modules/playwright-core/lib/server/chromium/chromium.js:122:33)
    at Chromium._innerLaunch (/server/node_modules/playwright-core/lib/server/browserType.js:161:32)
    at async Chromium._innerLaunchWithRetries (/server/node_modules/playwright-core/lib/server/browserType.js:120:14)
    at async ProgressController.run (/server/node_modules/playwright-core/lib/server/progress.js:82:22)
    at async Chromium.launch (/server/node_modules/playwright-core/lib/server/browserType.js:79:21)
    at async BrowserServerLauncherImpl.launchServer (/server/node_modules/playwright-core/lib/browserServerImpl.js:48:21) {
  type: 'closed',
  method: 'Browser.getVersion',
  logs: '\n' +
    '<launching> /usr/bin/chromium --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding,ThirdPartyStoragePartitioning,LensOverlay,PlzDedicatedWorker --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --headless=old --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-gBHnPg --remote-debugging-pipe --no-startup-window\n' +
    '<launched> pid=18\n' +
    '[pid=18][err] Error relocating /usr/lib/libgio-2.0.so.0: statx: symbol not found\n' +
    '[pid=18][err] Error relocating /usr/lib/libmount.so.1: statx: symbol not found\n' +
    '[pid=18] <process did exit: exitCode=127, signal=null>\n' +
    '[pid=18] starting temporary directories cleanup'
}

Node.js v23.0.0```

**Comment by loorisr** [comment]
Hello,
I have the same issue with playwright:chromium-light-server.  playwright:chromium-server is working fine.

**Comment by JacobLinCool** [comment]
`docker run --rm -p 53333:53333 jacoblincool/playwright:chromium-light-server` should work now.

**Comment by JacobLinCool** [comment]
If the issue persists, feel free to reopen it.

**Comment by azertylr** [comment]
it works, thanks!
